# File: .github/workflows/repo-sync.yml

on: push

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: repo-sync
      uses: repo-sync/github-sync@v2
      with:
        source_repo: FlyBase/harvdev-proforma-testdb
        source_branch: master
        destination_branch: multiple
        github_token: ${{ secrets.ACCESS_TOKEN }}
